language: python
python:
- 3.6
- 3.6-dev
install:
- pip install -r test_requirements.txt
- pip install tenacity==4.4.0 dill
- pip install git+https://github.com/seung-lab/DynamicAnnotationDB.git#egg=dynamicannotationdb
- pip install git+https://github.com/fcollman/PyChunkedGraph.git
- pip install -r requirements.txt
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- gcloud --quiet components install beta
script:
- python setup.py pytest
cache:
- pip: true
  directories:
  - "$HOME/google-cloud-sdk/"
after_success:
- codecov
deploy:
  provider: gae
  keyfile: client-secret.json
  project: neuromancer-seung-import
before_install:
- openssl aes-256-cbc -K $encrypted_7a12347eb83e_key -iv $encrypted_7a12347eb83e_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
