language: python
python:
- 3.6
- 3.6-dev
install:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- gcloud --quiet components install beta
- pip install -r test_requirements.txt
- pip install tenacity==4.4.0 dill
- pip install -r requirements.txt
script:
- python setup.py pytest
cache:
- pip: true
  directories:
  - "$HOME/google-cloud-sdk/"
after_success:
- codecov
- "git clone https://gist.github.com/2c04596a45ccac57fe8dde0718ad58ee.git /tmp/travis_automerge"
- "chmod a+x /tmp/travis-automerge/auto_merge_travis_with_bumpversion.sh"
- "BRANCHES_TO_MERGE_REGEX='develop' BRANCH_TO_MERGE_INTO=master /tmp/travis-automerge/auto_merge_travis_with_bumpversion.sh"
- "git clone https://gist.github.com/cf9b261f26a1bf3fae6b59e7047f007a.git /tmp/travis-autodist"
- "chmod a+x /tmp/travis-autodist/pypi_dist.sh"
- "BRANCHES_TO_DIST='master' /tmp/travis-autodist/pypi_dist.sh"
