language: python

install:
- pip install -r test_requirements.txt
- pip install tenacity==4.4.0 dill 
- pip install -r requirements.txt
stages:
- test
- name: merge-deploy

script:
  # - gcloud version || true
  # - if [ ! -d "${HOME}/google-cloud-sdk/bin" ]; then rm -rf ${HOME}/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # # Add gcloud to $PATH
  # - source ${HOME}/google-cloud-sdk/path.bash.inc
  # - gcloud --quiet version
  # - gcloud --quiet components update
  # - gcloud --quiet components install beta
  - python setup.py pytest

cache:
  - pip: true
    # directories:
    # - "${HOME}/google-cloud-sdk/"

jobs:
  include:
    - python: 3.6
      after_success:
        - codecov
    - python: 3.7-dev
    - stage: merge-deploy
      name: "version bump and merge into master"
      python: 3.7
      install:
        - pip install bumpversion
      script:
        - "git clone https://gist.github.com/2c04596a45ccac57fe8dde0718ad58ee.git /tmp/travis-automerge"
        - "chmod a+x /tmp/travis-automerge/auto_merge_travis_with_bumpversion.sh"
        - "BRANCHES_TO_MERGE_REGEX='develop' BRANCH_TO_MERGE_INTO=master /tmp/travis-automerge/auto_merge_travis_with_bumpversion.sh"
    - stage: merge-deploy
      name: "deploy to pypi"
      python: 3.7
      install:
        - pip install twine
      script: 
        - "git clone https://gist.github.com/cf9b261f26a1bf3fae6b59e7047f007a.git /tmp/travis-autodist"
        - "chmod a+x /tmp/travis-autodist/pypi_dist.sh"
        - "BRANCHES_TO_DIST='develop' /tmp/travis-autodist/pypi_dist.sh"
