version: '3'
services:
  app:
    image: 'annotation:tag'
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8082:4001
    volumes:
      - .:/app
    env_file:
      - ./.env-docker.dev
    command: python run.py
  db:
    image: mdillon/postgis
    env_file:
      - ./.env-docker.dev
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./entrypoint.sh:/var/lib/postgresql/entrypoint.sh
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
  #     retries: 5

volumes:
  postgres_data:
