"""Initial Migration

Revision ID: 3990f7706b40
Revises: 
Create Date: 2022-04-27 13:22:24.424657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3990f7706b40"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysisversion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datastack", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("time_stamp", sa.DateTime(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=True),
        sa.Column("expires_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotation_table_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schema_type", sa.String(length=100), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference_table", sa.String(length=100), nullable=True),
        sa.Column("flat_segmentation_source", sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_name"),
    )
    op.create_table(
        "analysistables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aligned_volume", sa.String(length=100), nullable=False),
        sa.Column("schema", sa.String(length=100), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("analysisversion_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysisversion_id"],
            ["analysisversion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "combined_table_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference_table", sa.String(length=100), nullable=True),
        sa.Column("annotation_table", sa.String(length=100), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "reference_table <> annotation_table", name="not_self_referenced"
        ),
        sa.ForeignKeyConstraint(
            ["annotation_table"],
            ["annotation_table_metadata.table_name"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_table"],
            ["annotation_table_metadata.table_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segmentation_table_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schema_type", sa.String(length=100), nullable=False),
        sa.Column("table_name", sa.String(length=100), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.DateTime(), nullable=True),
        sa.Column("segmentation_source", sa.String(length=255), nullable=True),
        sa.Column("pcg_table_name", sa.String(length=255), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("annotation_table", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["annotation_table"],
            ["annotation_table_metadata.table_name"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("segmentation_table_metadata")
    op.drop_table("combined_table_metadata")
    op.drop_table("analysistables")
    op.drop_table("annotation_table_metadata")
    op.drop_table("analysisversion")
    # ### end Alembic commands ###
