"""Add Voxel Resolution

Revision ID: 84da6b22778a
Revises: 3990f7706b40
Create Date: 2022-04-27 13:24:58.072171

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84da6b22778a"
down_revision = "3990f7706b40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "annotation_table_metadata",
        sa.Column("voxel_resolution_x", sa.Float(), nullable=False, server_default="1"),
    )
    op.add_column(
        "annotation_table_metadata",
        sa.Column("voxel_resolution_y", sa.Float(), nullable=False, server_default="1"),
    )
    op.add_column(
        "annotation_table_metadata",
        sa.Column("voxel_resolution_z", sa.Float(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("annotation_table_metadata", "voxel_resolution_z")
    op.drop_column("annotation_table_metadata", "voxel_resolution_y")
    op.drop_column("annotation_table_metadata", "voxel_resolution_x")
    # ### end Alembic commands ###
